packaging_format = 2

id = "paperless-ngx"
name = "paperless-ngx"
description.en = "Scan, index and archive all your physical documents"
description.fr = "Scannez, triez et archivez tous vos documents papiers"

version = "2.11.1~ynh1"

maintainers = ["Nikita Karamov"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paperless-ngx.com"
demo = "https://demo.paperless-ngx.com/"
admindoc = "https://paperless-ngx.readthedocs.io/en/latest/index.html"
userdoc = "https://paperless-ngx.readthedocs.io/en/latest/usage_overview.html"
code = "https://github.com/paperless-ngx/paperless-ngx"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "350M"
ram.runtime = "350M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.admin_pw]
    ask.en = "Please chose a password for admin user."
    type = "password"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.init_api_permission]
    ask.en = "Paperless-ngx API access list"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/paperless-ngx/paperless-ngx/releases/download/v2.11.1/paperless-ngx-v2.11.1.tar.xz"
        sha256 = "0dedc1e9fa742380c2b99aee11bf1f76e20fc8e8fba2c0fb50a11a3742c99a6a"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "paperless-ngx-.*.tar.xz"

        [resources.sources.gs]
        url = "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10021/ghostpdl-10.02.1.tar.gz"
        sha256 = "25399af0ef5bb94f2a13c91dc785c128d14f16744c4c92fa7c86e011c23151d8"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["consume", "data", "media", "imagemagick"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    api.url = "/api/"
    api.show_tile = false
    api.auth_header = false

    share.url = "/share/"
    share.show_tile = false
    share.auth_header = false
    share.protected = true
    share.allowed = "visitors"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "python3, python3-pip, python3-dev, python3-venv, default-libmysqlclient-dev, fonts-liberation, imagemagick, gnupg, libpq-dev, libmagic-dev, mime-support, libzbar0, poppler-utils, postgresql, postgresql-contrib, unpaper, ghostscript, icc-profiles-free, qpdf, liblept5, libxml2, pngquant, zlib1g, tesseract-ocr, libatlas-base-dev, libxslt1-dev, redis-server, pkg-config"

    [resources.database]
    type = "postgresql"
